name: rick_and_morty
description: A rick and morty characters list app for Flutter GetX workshop.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: 4.0.6                                  # https://pub.dev/packages/dio
  extended_image: 6.3.2                       # https://pub.dev/packages/extended_image
  flutter_fimber: 0.6.5                       # https://pub.dev/packages/flutter_fimber
  get: 4.6.5                                  # https://pub.dev/packages/get
  pretty_dio_logger: 1.2.0-beta-1             # https://pub.dev/packages/pretty_dio_logger/versions/1.2.0-beta-1
  cupertino_icons: 1.0.5                      # https://pub.dev/packages/cupertino_icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1                        # https://pub.dev/packages/flutter_lints

flutter:
  uses-material-design: true

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay.ttf
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi.ttf